In [ ]:
''' 
Numpy Library 

Numpy -> Numeric Python (all mathematical concept is supported by numpy)
'''
'''
Python List -> []
-> mutable 
-> ordered
-> multiple datatype but numpy doesn't 
priority order -> str > complex > float > int
'''

In [6]:
arr = ["a", 1, 4.0, 2+6j] 
print(arr)

['a', 1, 4.0, (2+6j)]


In [ ]:
import numpy as np
arr = np.array([1, 4.0, '2a'])
print(arr) # it created array of same datatypes 

for i in arr:
    print(f"{i} -> {type(i)}")

[1. 4. 2.]
1.0 -> <class 'numpy.float64'>
4.0 -> <class 'numpy.float64'>
2.0 -> <class 'numpy.float64'>


In [27]:
import numpy as np

In [ ]:

#? Numpy Array Creation
'''
1. using array method (Custom array building)
'''
arr = np.array([[1,2,3,4]])
print(arr)

[[1 2 3 4]]


In [33]:
arr.shape # shape of array (4,)

(1, 4)

In [30]:
arr = np.array(
    [[1,2,3],
     [4,5,6], 
     [7,8,9]]
) # 3X3 Matrix
arr.shape

(3, 3)

In [ ]:
arr = np.array([
    [1],
    [2],
    [3],
    [4]
])
arr.shape

(4, 1)

$$
A - \lambda I = 0
$$

Now we have to find solution (finding all possible values of $\lambda$)

In [ ]:
''' 
2. Zeros Numpy array of custom shape

shape - (2,2)

[[0,0], 
 [0,0]] 

0 (int zero) -> 0. (float zero)
int -> 0 
float -> 0.

eigenvalue(multiple lambda values) and eigenvector(A * lambda (column matrix)) (PCA) [Principal Component Analysis]
-> let say you have a matrix A, It has 20 columns and 1000 rows of data (1000,20)

ML model building 

(1000, 20)  -> (1000, 8) (without loss of any information)
A        -       lambda I         =         0
(matrix)         (matrix)               (matrix)
'''
arr = np.zeros((10,10), dtype=int)
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
''' 
3. Creation of Random Numpy array
'''
arr = np.random.rand(5) # it generated array of length 5 with random values (0 to 1)
print(arr)

[0.46037603 0.74455281 0.11013489 0.16887574 0.3765672 ]


In [ ]:
arr = np.arange(1,9,2) # continous range of values (numpy array)
''' 
range(1,9,2) 

range(start,end,step)

start=1, end=10, step=2
'''
print(arr) 

[1 3 5 7]


In [58]:
arr = np.random.randint(0,1000,size=(2,8)) 
# it will create (3,3) matrix each value is between range (0 to 10)
print(arr)

[[586 445 147 579 115 209 691  28]
 [628 892 180 494 929 255 931 175]]


In [67]:
''' 
Dimensions -> In which degree of freedom you can freely move

0D ->   ., 1, 2, 3, 4, 5, .... single numbers (constant)

1D -> [1] ->  left<->right or top<->bottom

2D -> left<->right and top<->bottom

[[1,2,3,4,5,6]
 [2,4,5,7,8,9]
 [3,4,5,6,8,9]]

.... ND

'''
arr1 = np.array([1,2,3,4]) # shape -> 4, dim -> 1D
arr2 = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]]     # ndim = 2
)
arr3 = np.array(
[
    [
        [1,2,3],
        [4,5,6]
    ],

    [
        [7,8,9],
        [1,2,3]
    ]       # ndim = 3
]
)

In [68]:
arr3.shape

(2, 2, 3)

In [65]:
arr = np.array([20000000000000000])
print(arr.ndim)

1


In [73]:
''' 
Indexing -> postive, negative, and slicing
'''     
arr = np.array([1,2,3,4])
print(arr[-1]) # 4
print(arr[-3]) # 2
print(arr[2:3]) # [3]
print(arr[-1:-3:-1]) # [4 3]
# [4,3,2,1]
print(arr[::-1])

4
2
[3]
[4 3]
[4 3 2 1]


In [ ]:
''' 
Reshaping your numpy array

(4,4) -> (2,5) -> 16 = 10
[[1,2,3,4]
 [1,2,3,4]
 [1,2,3,4]
 [1,2,3,4]]

[[1,2,3,4,1,2,3,4], 
 [1,2,3,4,1,2,3,4]]
'''

arr = np.array(
    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]]
)
print(arr)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
arr = arr.reshape((2,8))
print(arr)

[[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]]


In [ ]:
''' 
Operation in numpy
'''

a = np.array([1,2,3])
b = np.array([1,2,4])
print(a+b) # [True True False]

[2 4 7]


In [ ]:
''' 
Comparison
'''
a = np.array([1,2,3])
b = np.array([1,2,4])
print(np.equal(a,b)) # a==b
print(np.less(a,b)) # a<b
print(np.less_equal(a,b)) # a <= b
print(np.not_equal(a,b)) # a != b

[ True  True False]
[False False  True]
[ True  True  True]


In [113]:
''' 
Pandas
%pip install pandas
'''
import pandas as pd

In [114]:
''' 
Creation Array Using Pandas
'''
data = pd.array([1,2,3,4])
print(data)

<IntegerArray>
[1, 2, 3, 4]
Length: 4, dtype: Int64


In [115]:
int_array = pd.array([1,2,3,4], dtype=int)
float_array = pd.array([1,2,3,4,5], dtype=float)
str_array = pd.array(["aakash", "Aryan"], dtype=str)
print(int_array)
print(float_array)
print(str_array)

<NumpyExtensionArray>
[1, 2, 3, 4]
Length: 4, dtype: int64
<NumpyExtensionArray>
[1.0, 2.0, 3.0, 4.0, 5.0]
Length: 5, dtype: float64
<NumpyExtensionArray>
['aakash', 'Aryan']
Length: 2, dtype: str192


In [ ]:
'''
arr = [1,2,3,4] # class list
arr[0] # int


Pandas has 2 datatypes 
-> Series (1 column to work with) -> array/list (Python)
-> Dataframe (multiple columns) -> (Excel file -> csv file -> json) -> dictionary (Python)
'''

In [117]:
arr_series = pd.Series([1,2,3,4], name="Marks")
print(arr_series)

0    1
1    2
2    3
3    4
Name: Marks, dtype: int64


In [151]:
''' 
name_list = []
for i in range(10):
    name_list.append(chr(65+i))

chr() => ascii value to original value
65 -> 'A' 
66 -> 'B'
.
.
.
91 -> 'Z'
'''

name_list = [chr(65+i) for i in range(10)] # List Comprehention
print(name_list)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']


In [162]:
df = pd.DataFrame(data={
    "Name": name_list,
    "Marks": np.random.randint(10,20,10), 
    "Class": np.random.choice(["XI", "XII"], 10)
})
df

,Name,Marks,Class
0,A,15,XII
1,B,12,XII
2,C,12,XI
3,D,18,XII
4,E,10,XI
5,F,15,XI
6,G,13,XII
7,H,18,XII
8,I,11,XII
9,J,10,XII


In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Marks   10 non-null     int32 
 2   Class   10 non-null     object
dtypes: int32(1), object(2)
memory usage: 332.0+ bytes


In [164]:
df.describe()

,Marks
count,10.000000
mean,13.400000
std,2.988868
min,10.000000
25%,11.250000
50%,12.500000
75%,15.000000
max,18.000000


In [165]:
# addition of new column in dataframe
df["Height"] = np.random.randint(150,180,10)
df

,Name,Marks,Class,Height
0,A,15,XII,171
1,B,12,XII,167
2,C,12,XI,168
3,D,18,XII,175
4,E,10,XI,172
5,F,15,XI,173
6,G,13,XII,165
7,H,18,XII,158
8,I,11,XII,168
9,J,10,XII,165


In [166]:
# removal of column from dataframe
''' 
drop -> axis = 1 -> column 
        axis = 0 -> row
'''
df.drop(["Name"], axis=1, inplace=True)

In [167]:
df

,Marks,Class,Height
0,15,XII,171
1,12,XII,167
2,12,XI,168
3,18,XII,175
4,10,XI,172
5,15,XI,173
6,13,XII,165
7,18,XII,158
8,11,XII,168
9,10,XII,165


In [169]:
# df.drop([8,9], axis=0, inplace=True)
df

,Marks,Class,Height
0,15,XII,171
1,12,XII,167
2,12,XI,168
3,18,XII,175
4,10,XI,172
5,15,XI,173
6,13,XII,165
7,18,XII,158


In [159]:
df.to_csv("data.csv", index=False)

In [142]:
df.to_excel("data.xlsx", index=False)

In [143]:
df.to_json("data.json", index=False)

In [160]:
df = pd.read_csv("data.csv")
df.head()

,Marks,Class,Height
0,14,XII,158
1,11,XII,179
2,19,XII,164
3,10,XI,173
4,12,XII,170


In [ ]:
import pandas as pd 
df = pd.read_csv("https://gist.githubusercontent.com/garrettgman/9629323/raw/ee5dfc039fd581cb467cc69c226ea2524913c3d8/deck.csv")
df

,face,suit,value
0,king,spades,13
1,queen,spades,12
2,jack,spades,11
3,ten,spades,10
4,nine,spades,9
5,eight,spades,8
6,seven,spades,7
7,six,spades,6
8,five,spades,5
9,four,spades,4


In [3]:
import sqlite3 
import pandas as pd 

db_path = "student.db"

conn = sqlite3.connect(db_path)

In [4]:
data = {
    "id": [1,2,3], 
    "name": ["Amit", "Sara", "John"], 
    "class": ["10A", "10B", "10C"], 
    "marks": [85,90,78]
}
df = pd.DataFrame(data=data)
df.to_sql("students", conn, if_exists="replace", index=False)

3